language: python

python:
    - "3.6.3"

notifications:
  email: false

branches:
  only:
    - repos-source

before_install:
    - echo $HELLO!
    - sudo apt-get update

install:
    - sudo /home/travis/virtualenv/python3.6.3/bin/python -m pip install -r requirements.txt
    - pip list
    - ls

script:
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - git config --global push.default simple
    - git checkout repos-source
    - git clone --depth 1 -b repos-backup https://$GH_TOKEN@github.com/$GH_REPO_SLUG repos-backup
    # - shopt -s extglob
    # - rm -rf repos-backup/*bundle
    - python manage.py
    - ls -F -lh ./repos-backup

after_success:
    # 输出最后一次 commit 到文件
    - git show -1 -s --format="$(echo %B$'\n'%H)" > commit-msg.tmp
    - cd repos-backup
    - git config --local -l
    - git add .
    - git commit -F ../commit-msg.tmp
    - git push --force --quiet "https://$GH_TOKEN@github.com/$GH_REPO_SLUG" repos-backup:repos-backup

