language: python

python:
    - "3.6"

notifications:
  email: false

branches:
  only:
    - repos-source

before_install:
    - echo $HELLO!
    - sudo apt-get update

install:
    - sudo pip install -r requirements.txt

script:
    - pip list
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - git config --global push.default simple
    - git checkout repos-source
    - git clone --recursive --depth 1 https://github.com/Drake-Z/github-repo-backup repos-backup
    - cd repos-backup
    - python manage.py
    - cd ..

after_success:
    # 输出最后一次 commit 到文件
    - git show -1 -s --format="$(echo %B$'\n'%H)" > commit-msg.tmp
    - cd repos-backup
    - git add -A .
    # 加载 blog-source commit 文件
    - git commit -F ../commit-msg.tmp
    - git push --force --quiet "https://$GH_TOKEN@github.com/$GH_REPO_SLUG" repos-backup:repos-backup
